
// Projects data - accessible globally as it's loaded via script tag
const projects = [
  {
    "id": "1",
    "title": "Modern Apartment Complex",
    "coverImage": "images/projects/apartments/1.jpg",
    "images": ["images/projects/apartments/1.jpg"],
    "hero": "icons/Buildings/building-line.svg",
    "description": "Situated in the dynamic urban fabric of Addis Ababa, this apartment complex prioritizes sustainable living with natural ventilation and daylighting strategies. The building's façade incorporates locally sourced stone blended with sleek glass panels, creating an elegant yet culturally resonant aesthetic. The project fosters community with shared outdoor terraces and green spaces, balancing urban density with wellness. Each unit features modern amenities while maintaining energy efficiency through passive design principles.",
    "year": "2008",
    "client": "Robi Business Group",
    "type": "Apartment",
    "cost": "~",
    "location": "Addis Ababa, Ethiopia",
    "challenges": "Integrating green spaces within tight urban context while maintaining cultural authenticity. Balancing modern amenities with traditional architectural elements. Managing construction costs while implementing sustainable features.",
    "tags": ["Buildings", "Design"]
  },
  {
    "id": "2",
    "title": "Luxury Urban Residence",
    "coverImage": "images/projects/apartments/2.jpg",
    "images": ["images/projects/apartments/2.jpg"],
    "hero": "icons/Buildings/home-line.svg",
    "description": "This upscale residence in Addis Ababa fuses cutting-edge smart home technology with traditional Ethiopian architectural motifs. Featuring high-efficiency building envelopes and solar shading, the design reduces energy consumption while offering luxurious comfort. Interiors emphasize open-plan layouts enhancing natural flow and connection to outdoor spaces. The residence showcases premium materials and finishes, creating a sophisticated living environment that respects local heritage.",
    "year": "2023",
    "client": "Engineer Diriba Defersha",
    "type": "Apartment",
    "cost": "92Million",
    "location": "Addis Ababa, Ethiopia",
    "challenges": "Integrating advanced technology with cultural design references harmoniously. Cost was a significant factor in material selection. Coordinating multiple contractors for specialized systems installation.",
    "tags": ["Technology", "Buildings"]
  },
  {
    "id": "3",
    "title": "Affordable Housing Block",
    "coverImage": "images/projects/apartments/3.png",
    "images": ["images/projects/apartments/3.png"],
    "hero": "icons/Buildings/building-2-line.svg",
    "description": "Designed to improve urban living standards in Addis Ababa, this affordable housing block balances cost effectiveness with quality housing. Utilizing prefabricated materials and efficient layouts, it provides comfortable, sustainable homes for multi-family occupancy. Green courtyards enhance community interaction and environmental quality. The project demonstrates how thoughtful design can create dignified living spaces within budget constraints.",
    "year": "2022",
    "client": "Ato Adane Neguse",
    "type": "Apartment",
    "cost": "102Million",
    "location": "Addis Ababa, Ethiopia",
    "challenges": "Maximizing space and minimizing costs without compromising resident comfort. Sourcing affordable yet durable materials. Managing construction timeline with limited resources.",
    "tags": ["Buildings", "Development"]
  },
  {
    "id": "4",
    "title": "Kokeb Real Estate Development",
    "coverImage": "images/projects/apartments/4.jpg",
    "images": ["images/projects/apartments/4.jpg", "images/projects/apartments/4.1.jpg"],
    "hero": "icons/Buildings/building-2-line.svg",
    "description": "This comprehensive real estate development in Addis Ababa represents a modern approach to urban living. The project combines residential units with commercial spaces, creating a vibrant mixed-use community. The design emphasizes walkability and social interaction, with carefully planned public spaces and amenities. Sustainable building practices and energy-efficient systems ensure long-term value for residents and investors.",
    "year": "2022",
    "client": "Kokeb Real Estate",
    "type": "Apartment",
    "cost": "~",
    "location": "Addis Ababa, Ethiopia",
    "challenges": "Coordinating multiple building types within a single development. Managing stakeholder expectations across different user groups. Implementing sustainable features while maintaining profitability.",
    "tags": ["Buildings", "Apartment", "Home", "Development"]
  },
  {
    "id": "5",
    "title": "Sebkete Wegel Hall - Community Assembly Hall",
    "coverImage": "images/projects/assembly hall/1.jpg",
    "images": ["images/projects/assembly hall/1.2.png"],
    "hero": "icons/User & Faces/group-line.svg",
    "description": "This community assembly hall in Addis Ababa serves diverse community needs from public meetings to cultural events. The flexible interior includes retractable seating and advanced acoustics to optimize sound. Large windows create a visual connection to the surrounding park, fostering openness and social engagement. The building serves as a cultural hub, hosting everything from religious services to community celebrations and educational programs.",
    "year": "2012",
    "client": "Bole Medhanealem Church Committee",
    "type": "Assembly",
    "cost": "102Million",
    "location": "Addis Ababa, Ethiopia",
    "challenges": "Achieving acoustic excellence and spatial flexibility within budget constraints. Balancing traditional architectural elements with modern functionality. Managing construction during active community use.",
    "tags": ["Buildings", "Church", "User & Faces", "Communication"]
  },
  {
    "id": "6",
    "title": "Rural Assembly Hall",
    "coverImage": "images/projects/assembly hall/2.jpg",
    "images": ["images/projects/assembly hall/2.jpg"],
    "hero": "icons/Buildings/building-line.svg",
    "description": "Conceived as a cornerstone of rural community life near Addis Ababa, this assembly hall champions vernacular construction techniques using locally harvested timber, clay bricks, and thatch roofing. The expansive single-volume space features exposed beam construction that celebrates traditional craftsmanship while accommodating diverse functions from weekly markets to seasonal festivals. Strategically positioned openings provide cross-ventilation and frame views of the surrounding agricultural landscape.",
    "year": "2021",
    "client": "Rural Development Agency",
    "type": "Assembly",
    "cost": "~",
    "location": "Addis Ababa, Ethiopia",
    "challenges": "Training local builders in seismic-resistant construction methods using traditional materials. Establishing supply chains for quality timber while supporting local forestry practices. Creating weather-tight construction details without modern sealants.",
    "tags": ["Buildings", "Community"]
  },
  {
    "id": "7",
    "title": "Historic Church Restoration",
    "coverImage": "images/projects/church/1.jpg",
    "images": ["images/projects/church/1.jpg"],
    "hero": "icons/Buildings/church-line.svg",
    "description": "This meticulous restoration of a centuries-old Gojam church required extensive archaeological documentation and specialized conservation techniques. Hand-carved wooden elements were carefully restored using traditional joinery methods, while ancient murals underwent scientific cleaning and stabilization. Modern structural reinforcement was invisibly integrated to meet seismic requirements. The project included training local craftspeople in heritage conservation techniques to ensure long-term maintenance capabilities.",
    "year": "2015",
    "client": "Mertu Le Mariyam Church Committee",
    "type": "Church",
    "cost": "~",
    "location": "Gojam, Ethiopia",
    "challenges": "Sourcing artisans skilled in 16th-century construction techniques. Developing custom conservation treatments for deteriorated religious artwork. Balancing UNESCO heritage guidelines with active worship requirements.",
    "tags": ["Buildings", "Church", "Cultural"]
  },
  {
    "id": "8",
    "title": "Church Building",
    "coverImage": "images/projects/church/2.jpg",
    "images": ["images/projects/church/2.jpg", "images/projects/church/2.1.jpg"],
    "hero": "icons/Buildings/building-line.svg",
    "description": "This contemporary church in Addis Ababa reimagines traditional Ethiopian Orthodox architecture through a modern lens. The design features a distinctive copper-clad bell tower that develops a natural patina over time, while the main sanctuary incorporates handcrafted wooden screens that filter light and create intimate prayer spaces. Underfloor radiant heating and natural wool insulation ensure year-round comfort. Community rooms with retractable walls adapt to various congregation sizes and social functions.",
    "year": "2014",
    "client": "CMC St Michael Building Committee",
    "type": "Church",
    "cost": "204Million",
    "location": "Addis Ababa, Ethiopia",
    "challenges": "Developing custom acoustic treatments for Ethiopian Orthodox liturgical requirements. Integrating traditional iconographic elements with contemporary structural systems. Coordinating artisan schedules with construction milestones.",
    "tags": ["Buildings", "Church", "Design"]
  },
  {
    "id": "9",
    "title": "Small Church Building",
    "coverImage": "images/projects/church/3.jpg",
    "images": ["images/projects/church/3.jpg"],
    "hero": "icons/Buildings/church-line.svg",
    "description": "Nestled in historic Gondar, this intimate chapel maximizes spiritual impact within minimal square footage through carefully orchestrated proportions and lighting. The design employs a traditional cruciform plan with a central dome that draws the eye upward, while stained glass windows cast colorful patterns across handwoven textile wall hangings. Local volcanic stone provides thermal mass and connects the building to its geological context. A covered outdoor gathering space extends the usable area for fellowship activities.",
    "year": "2022",
    "client": "St Medhanealem Church Committee",
    "type": "Church",
    "cost": "65Million",
    "location": "Gondar, Ethiopia",
    "challenges": "Achieving monumental scale within strict spatial limitations. Sourcing quality stained glass artisans within budget constraints. Managing construction in densely built historic neighborhood.",
    "tags": ["Buildings", "Church", "Design"]
  },
  {
    "id": "10",
    "title": "Church Building",
    "coverImage": "images/projects/church/4.jpg",
    "images": ["images/projects/church/4.jpg"],
    "hero": "icons/Buildings/church-line.svg",
    "description": "This parish church in Addis Ababa demonstrates adaptive reuse principles by transforming a former warehouse into a vibrant spiritual center. High ceilings and industrial steel trusses were retained and celebrated, while new insertions include a floating mezzanine for choir seating and a baptismal pool with natural stone surround. Clerestory windows flood the space with diffused light, while polished concrete floors with radiant heating provide comfort. The adjacent social hall features a commercial kitchen for community meals.",
    "year": "2013",
    "client": "Keraniyo Gabreal Church Committee",
    "type": "Church",
    "cost": "215Million",
    "location": "Addis Ababa, Ethiopia",
    "challenges": "Adapting industrial building systems to religious programming requirements. Meeting fire safety codes for large assemblies within existing structure. Balancing preservation of industrial character with sacred atmosphere.",
    "tags": ["Buildings", "Church", "Design"]
  },
  {
    "id": "11",
    "title": "Church Building",
    "coverImage": "images/projects/church/5.jpg",
    "images": ["images/projects/church/5.jpg"],
    "hero": "icons/Buildings/church-line.svg",
    "description": "This forward-thinking church in Addis Ababa embraces digital age worship while honoring ancient traditions. The building features integrated projection systems and wireless connectivity throughout, enabling multimedia services and remote participation. A living wall system purifies indoor air while creating a contemplative garden atmosphere. Solar panels integrated into the roof design generate renewable energy, while rainwater harvesting supplies irrigation. The flexible sanctuary can be reconfigured for concerts, lectures, and community theater.",
    "year": "2025",
    "client": "Dessie Urael Church Committee",
    "type": "Church",
    "cost": "102Million",
    "location": "Addis Ababa, Ethiopia",
    "challenges": "Integrating cutting-edge technology without compromising spiritual authenticity. Designing building systems for maximum flexibility and future adaptability. Balancing sustainability goals with construction budget realities.",
    "tags": ["Buildings", "Church", "Design"]
  },
  {
    "id": "12",
    "title": "Church Building",
    "coverImage": "images/projects/church/6.jpg",
    "images": ["images/projects/church/6.jpg"],
    "hero": "icons/Buildings/building-line.svg",
    "description": "This innovative church represents a new paradigm in Ethiopian ecclesiastical design, featuring a dramatic tensioned fabric roof that creates column-free interior spaces. Geothermal heating and cooling systems maintain optimal comfort while minimizing environmental impact. The design includes a meditation labyrinth, therapeutic gardens, and contemplative water features that support spiritual wellness. Modular furniture systems allow the space to transform from intimate prayer circles to large congregational gatherings within minutes.",
    "year": "2023",
    "client": "St. Gabriel Church Committee",
    "type": "Church",
    "cost": "~",
    "location": "Addis Ababa, Ethiopia",
    "challenges": "Engineering complex tensioned roof structure in seismic zone. Developing innovative geothermal systems for Ethiopian climate conditions. Creating seamless transitions between indoor and outdoor sacred spaces.",
    "tags": ["Buildings", "Church", "Design"]
  },
  {
    "id": "13",
    "title": "Church Building",
    "coverImage": "images/projects/church/7.png",
    "images": ["images/projects/church/7.png"],
    "hero": "icons/Buildings/church-line.svg",
    "description": "This distinguished church building exemplifies Ethiopian ecclesiastical architecture through its masterful use of proportion, materials, and light. Hand-selected Ethiopian marble creates a luminous interior, while custom-forged bronze fixtures and furnishings celebrate local metalworking traditions. The sanctuary features a suspended baldachin that defines the altar space without obstructing sightlines. Acoustic design incorporates sound-absorbing tapestries and carefully tuned surfaces to optimize both spoken word and choral music.",
    "year": "2019",
    "client": "St Mariyam Church Committee",
    "type": "Church",
    "cost": "~",
    "location": "Addis Ababa, Ethiopia",
    "challenges": "Sourcing and matching Ethiopian marble from multiple quarries. Coordinating traditional metalworking with modern structural requirements. Achieving perfect acoustic balance for diverse liturgical practices.",
    "tags": ["Buildings", "Church"]
  },
  {
    "id": "14",
    "title": "Compound Entrance Gate",
    "coverImage": "images/projects/church/8.jpg",
    "images": ["images/projects/church/8.jpg"],
    "hero": "icons/Buildings/church-line.svg",
    "description": "This monumental entrance gate serves as both threshold and symbol, marking the transition from secular to sacred space. The design features traditional Ethiopian crosses wrought in contemporary steel, while integrated LED lighting creates dramatic nighttime illumination. Biometric access systems ensure security without compromising the welcoming atmosphere. The structure incorporates a pilgrimage rest area with stone benches and shade trees, acknowledging the building's role in community life beyond worship services.",
    "year": "2008",
    "client": "Bole Medhanealem Church Committee",
    "type": "Church",
    "cost": "13Million",
    "location": "Addis Ababa, Ethiopia",
    "challenges": "Balancing symbolic importance with practical security requirements. Integrating modern access control with traditional design language. Creating durable construction able to withstand heavy daily use.",
    "tags": ["Buildings", "Church"]
  },
  {
    "id": "15",
    "title": "Church Building",
    "coverImage": "images/projects/church/9.jpg",
    "images": ["images/projects/church/9.jpg"],
    "hero": "icons/Buildings/church-line.svg",
    "description": "This thoughtful renovation preserves a beloved church's historical character while updating infrastructure for 21st-century needs. Original stonework was carefully cleaned and repointed, while new disabled-accessible entrances were seamlessly integrated. The electrical system was completely rewired with discrete conduits, and modern HVAC was installed using minimal visual impact. Original stained glass windows were restored and supplemented with new panels by contemporary Ethiopian artists, creating dialogue between past and present.",
    "year": "2014",
    "client": "Lebu, Kidist Arsema Church Committee",
    "type": "Church",
    "cost": "52Million",
    "location": "Addis Ababa, Ethiopia",
    "challenges": "Preserving architectural integrity while meeting current accessibility codes. Upgrading building systems without damaging historical fabric. Managing construction schedules around active worship services.",
    "tags": ["Buildings", "Church"]
  },
  {
    "id": "16",
    "title": "Church Building",
    "coverImage": "images/projects/church/10.jpg",
    "images": ["images/projects/church/10.jpg"],
    "hero": "icons/Buildings/church-line.svg",
    "description": "This multipurpose church facility serves as both spiritual center and community anchor, featuring expandable worship spaces that accommodate seasonal variations in attendance. The design includes dedicated spaces for religious education, community meetings, and cultural celebrations. A commercial kitchen supports meal programs and social events, while offices provide administrative functions. Sustainable features include a green roof system, solar hot water, and natural ventilation strategies that reduce operating costs.",
    "year": "2017",
    "client": "Gofa St. Urael Church Committee",
    "type": "Church",
    "cost": "160Million",
    "location": "Addis Ababa, Ethiopia",
    "challenges": "Creating flexible spaces that serve multiple community functions effectively. Balancing spiritual atmosphere with practical community center requirements. Managing complex programming within constrained urban site.",
    "tags": ["Buildings", "Church"]
  },
  {
    "id": "17",
    "title": "Church Building",
    "coverImage": "images/projects/church/11.jpg",
    "images": ["images/projects/church/11.jpg"],
    "hero": "icons/Buildings/church-line.svg",
    "description": "Located in Nazreth, the Adama Kidanemehret Church is a testament to architectural harmony, blending contemporary design principles with the rich heritage of Ethiopian ecclesiastical tradition. The design features a striking geometric facade that creates dynamic patterns of light and shadow within the main worship hall, fostering an atmosphere of spiritual reverence. By utilizing locally-sourced materials and prioritizing natural ventilation, the building not only respects its cultural context but also serves as a sustainable landmark for its congregation.",
    "year": "2018",
    "client": "Adama Kidanemehret Church Committee",
    "type": "Church",
    "cost": "158Million",
    "location": "Nazreth, Ethiopia",
    "challenges": "The primary challenge was to create a bold, modern form that remained respectful to sacred architectural traditions. Structurally, this involved engineering a complex roof system that allowed for a large, column-free interior space. Additionally, achieving superior acoustics for worship while working with hard, reflective surfaces required innovative material selection and design.",
    "tags": ["Buildings", "Church"]
  },
  {
    "id": "18",
    "title": "Church Building",
    "coverImage": "images/projects/church/12.jpg",
    "images": ["images/projects/church/12.jpg"],
    "hero": "icons/Buildings/church-line.svg",
    "description": "As a prominent feature in Addis Ababa's urban landscape, the Lebu St. Gabriel Church was conceived as a forward-thinking spiritual center. Its design is defined by a commitment to sustainability, incorporating passive cooling strategies and rainwater harvesting systems. The adaptable interior spaces are designed to serve a variety of community functions—from intimate services to large-scale cultural events—making it a versatile hub that reflects the dynamic needs of its congregation.",
    "year": "2024",
    "client": "Lebu St. Gabriel Building Committee",
    "type": "Church",
    "cost": "192Million",
    "location": "Addis Ababa, Ethiopia",
    "challenges": "Navigating the complexities of a dense urban site, including logistical constraints and strict zoning regulations, was a significant hurdle. Integrating advanced sustainable systems with the architectural form required close collaboration between engineers and designers. A key challenge was ensuring the building felt both monumental and welcoming, serving as an open spiritual home in a bustling city.",
    "tags": ["Buildings", "Church"]
  },
  {
    "id": "19",
    "title": "Clinic Building",
    "coverImage": "images/projects/clinic/1.jpg",
    "images": ["images/projects/clinic/1.jpg"],
    "hero": "icons/Buildings/clinic-line.svg",
    "description": "This modern medical facility in Nazareth prioritizes patient comfort through evidence-based design principles. The layout emphasizes clear wayfinding with intuitive circulation patterns, while natural materials and abundant daylight reduce institutional atmosphere. Specialized ventilation systems maintain sterile environments in treatment areas while ensuring energy efficiency. The building includes telemedicine capabilities, connecting rural patients with urban specialists through high-speed connectivity infrastructure.",
    "year": "2023",
    "client": "Mama Ethiopia Clinic",
    "type": "Clinic",
    "cost": "4.2Million",
    "location": "Nazareth, Ethiopia",
    "challenges": "Meeting stringent medical facility regulations within limited construction budget. Designing flexible treatment spaces adaptable to changing medical technologies. Ensuring reliable power systems for critical medical equipment.",
    "tags": ["Clinic", "Buildings"]
  },
  {
    "id": "20",
    "title": "Fuel Service Station",
    "coverImage": "images/projects/fuel service station/1.jpg",
    "images": ["images/projects/fuel service station/1.jpg", "images/projects/fuel service station/1.2.png", "images/projects/fuel service station/1.3.png"],
    "hero": "icons/Buildings/building-2-line.svg",
    "description": "This Total Energies station in Addis Ababa redefines the roadside service experience through innovative design and environmental responsibility. The distinctive canopy structure provides weather protection while showcasing the brand identity through integrated LED lighting systems. Advanced fuel management systems ensure safety and accuracy, while the convenience store features local Ethiopian products alongside international brands. Solar panels integrated into the canopy structure generate renewable energy for site operations.",
    "year": "2009",
    "client": "Total Energies Ethiopia",
    "type": "Fuel",
    "cost": "12Million + 15Million",
    "location": "Addis Ababa, Ethiopia",
    "challenges": "Meeting petroleum industry safety regulations while creating distinctive architectural identity. Managing complex utility coordination for fuel systems, electrical, and communications. Balancing corporate branding requirements with local aesthetic preferences.",
    "tags": ["Buildings", "Business"]
  },
  {
    "id": "21",
    "title": "Almaya University Hospital Building",
    "coverImage": "images/projects/hospital/1.png",
    "images": ["images/projects/hospital/1.png"],
    "hero": "icons/Buildings/hospital-line.svg",
    "description": "This state-of-the-art medical complex in Harar represents Ethiopia's commitment to advanced healthcare infrastructure. The facility integrates cutting-edge diagnostic equipment with patient-centered design, featuring healing gardens and natural light in patient rooms. The building includes specialized wings for emergency services, surgical suites, and intensive care, all connected by efficient circulation systems. Advanced building automation systems monitor air quality, temperature, and lighting to optimize healing environments while minimizing energy consumption.",
    "year": "2024",
    "client": "Alemaya University",
    "type": "Hospital",
    "cost": "1.8Billion",
    "location": "Harar, Ethiopia",
    "challenges": "Coordinating complex medical equipment installation with building systems. Meeting international healthcare facility standards in challenging site conditions. Managing construction logistics for remote location while maintaining quality standards.",
    "tags": ["Buildings", "Hospital"]
  },
  {
    "id": "22",
    "title": "Referral Hospital Building",
    "coverImage": "images/projects/hospital/2.png",
    "images": ["images/projects/hospital/2.png"],
    "hero": "icons/Buildings/building-line.svg",
    "description": "This regional medical center in Nazareth, Adama serves as a critical healthcare hub for central Ethiopia. The design emphasizes operational efficiency through optimal department adjacencies and clear circulation hierarchies. Patient-focused amenities include family waiting areas with natural light, meditation spaces, and therapeutic gardens. The building incorporates resilient design features including backup power systems, water storage, and flexible spaces that can adapt to emergency situations or changing medical needs.",
    "year": "2018",
    "client": "Adama Referral Hospital",
    "type": "Hospital",
    "cost": "2.0Billion",
    "location": "Nazareth, Adama, Ethiopia",
    "challenges": "Designing for complex medical workflows while maintaining infection control protocols. Creating family-friendly spaces within sterile medical environment. Ensuring building systems reliability for life-critical functions.",
    "tags": ["Buildings", "Hospital"]
  },
  {
    "id": "23",
    "title": "Luxury Hotel Building",
    "coverImage": "images/projects/hotel bldg/1.jpg",
    "images": ["images/projects/hotel bldg/1.jpg"],
    "hero": "icons/Business/briefcase-line.svg",
    "description": "This premium hospitality destination in Nazareth, Adama caters to business travelers and conference attendees with sophisticated amenities. The design features a dramatic atrium lobby with local artwork installations, while guest rooms offer panoramic views and smart room technology. Conference facilities include state-of-the-art audiovisual systems and flexible meeting spaces. The rooftop restaurant and bar provide spectacular sunset views, while the spa and fitness center offer relaxation amenities for discerning guests.",
    "year": "2020",
    "client": "Robi Groups Plc",
    "type": "Hotel",
    "cost": "185Million",
    "location": "Nazareth, Adama, Ethiopia",
    "challenges": "Creating luxury hospitality experience in emerging market conditions. Integrating complex building systems for guest comfort and operational efficiency. Balancing international hotel standards with local cultural preferences.",
    "tags": ["Business", "Hotel"]
  },
  {
    "id": "24",
    "title": "Mixed Use Hotel Building",
    "coverImage": "images/projects/hotel bldg/2.png",
    "images": ["images/projects/hotel bldg/2.png"],
    "hero": "icons/Buildings/home-line.svg",
    "description": "This early hospitality project in Nazareth, Adama established standards for affordable business travel accommodation in the region. The design maximizes efficiency through compact yet comfortable guest rooms, centralized building systems, and minimal maintenance requirements. Public spaces emphasize functionality over luxury, with practical furniture and durable finishes. The ground floor includes retail and dining options that serve both guests and the local community, creating an integrated mixed-use environment.",
    "year": "2006",
    "client": "Tetas Group Plc",
    "type": "Hotel",
    "cost": "12Million",
    "location": "Nazareth, Adama, Ethiopia",
    "challenges": "Achieving hospitality standards within extremely limited construction budget. Designing for low-maintenance operations in resource-constrained environment. Creating profitable mixed-use programming in developing market.",
    "tags": ["Buildings", "Hotel"]
  },
  {
    "id": "25",
    "title": "University Library Building",
    "coverImage": "images/projects/library/1.jpg",
    "images": ["images/projects/library/1.jpg", "images/projects/library/1.1.png"],
    "hero": "icons/Buildings/home-2-line.svg",
    "description": "This comprehensive academic library in Gondar transforms traditional research and learning through innovative spatial design and technology integration. The building features diverse study environments from silent individual carrels to collaborative group spaces, all connected by a central atrium that serves as an informal learning commons. Advanced climate control systems protect rare book collections while maintaining comfort in public areas. Digital infrastructure supports both traditional research and emerging educational technologies.",
    "year": "2022",
    "client": "University of Gondar",
    "type": "Library",
    "cost": "1.4Billion",
    "location": "Gondar, Ethiopia",
    "challenges": "Balancing preservation requirements for historical collections with modern digital infrastructure needs. Creating diverse learning environments within unified architectural concept. Managing acoustic separation between quiet study and collaborative areas.",
    "tags": ["Buildings", "Library"]
  },
  {
    "id": "26",
    "title": "Mixed Use Building",
    "coverImage": "images/projects/mixed use bldg/1.jpg",
    "images": ["images/projects/mixed use bldg/1.jpg"],
    "hero": "icons/Buildings/home-line.svg",
    "description": "This versatile mixed-use development in Addis Ababa demonstrates urban density done well, combining ground-floor retail, office spaces, and residential units in a cohesive architectural package. The design emphasizes pedestrian connectivity through covered walkways and public plazas that enliven the streetscape. Residential units feature private balconies and shared roof terraces, while commercial spaces benefit from flexible layouts and abundant natural light. Parking is integrated discretely to maintain street-level activation.",
    "year": "2024",
    "client": "Engineer Dirba Defersha",
    "type": "mixed-use",
    "cost": "210Million",
    "location": "Addis Ababa, Ethiopia",
    "challenges": "Reconciling conflicting requirements of residential privacy and commercial visibility. Managing complex zoning and building code requirements for mixed programming. Coordinating construction staging to minimize disruption to surrounding area.",
    "tags": ["Buildings", "Mixed Use"]
  },
  {
    "id": "27",
    "title": "Mixed Use Building",
    "coverImage": "images/projects/mixed use bldg/2.jpg",
    "images": ["images/projects/mixed use bldg/2.jpg"],
    "hero": "icons/Buildings/home-line.svg",
    "description": "This church-sponsored development in Addis Ababa provides both revenue generation and community services through thoughtful programming. The design includes rental apartments, office spaces for small businesses, and community meeting rooms available to local organizations. A central courtyard provides shared outdoor space while ensuring privacy for residential units. The architecture reflects traditional Ethiopian design principles while meeting modern building standards and accessibility requirements.",
    "year": "2024",
    "client": "St. Georgis Church Committee",
    "type": "mixed-use",
    "cost": "80Million",
    "location": "Addis Ababa, Ethiopia",
    "challenges": "Balancing church community needs with commercial viability requirements. Designing for diverse user groups with conflicting schedule and space needs. Managing project financing through traditional religious organization structures.",
    "tags": ["Buildings", "Mixed Use"]
  },
  {
    "id": "28",
    "title": "College Mixed Use Building",
    "coverImage": "images/projects/mixed use bldg/3.jpg",
    "images": ["images/projects/mixed use bldg/3.jpg"],
    "hero": "icons/Buildings/home-line.svg",
    "description": "This educational facility in Debre Zyet, Bishoftu combines academic programming with revenue-generating commercial spaces to support institutional sustainability. The design features classrooms, administrative offices, and student services integrated with retail and dining options. Flexible spaces accommodate changing educational needs, while technology infrastructure supports both traditional and distance learning modalities. The building serves as a community landmark while generating income to support educational programs.",
    "year": "2017",
    "client": "Meserete Kiresos College",
    "type": "Mmixed-use",
    "cost": "600Million",
    "location": "Debre Zyet, Bishoftu Town, Ethiopia",
    "challenges": "Creating synergy between educational and commercial programming without conflicts. Designing for complex security requirements with multiple user groups. Achieving educational facility standards while maintaining commercial viability.",
    "tags": ["Buildings", "Mixed Use"]
  },
  {
    "id": "29",
    "title": "Church Mixed Use Building",
    "coverImage": "images/projects/mixed use bldg/4.jpg",
    "images": ["images/projects/mixed use bldg/4.jpg", "images/projects/mixed use bldg/4.2.png", "images/projects/mixed use bldg/4.1.png"],
    "hero": "icons/Buildings/home-line.svg",
    "description": "Located in the heart of Addis Ababa, this church-owned mixed-use development combines retail units at street level with modern apartments above. The design integrates cultural architectural references with contemporary forms, while maximizing natural lighting and ensuring acoustic comfort between worship areas, residences, and businesses.",
    "year": "2013",
    "client": "St. Georgis Church Commitee",
    "type": "mixed-use",
    "cost": "250Million",
    "location": "Addis Ababa, Ethiopia",
    "challenges": "Integrating religious functions with commercial and residential uses without compromising privacy or spiritual ambiance.",
    "tags": ["Buildings", "Mixed Use"]
  },
  {
    "id": "30",
    "title": "Commercial Car display building",
    "coverImage": "images/projects/mixed use bldg/5.jpg",
    "images": ["images/projects/mixed use bldg/5.jpg", "images/projects/mixed use bldg/5.1.png"],
    "hero": "icons/Buildings/building-line.svg",
    "description": "This showroom in Bishoftu showcases vehicles in a light-filled, open-plan space framed by expansive glass facades. The layout is designed for smooth visitor circulation, with a visible workshop for customer transparency and a bold façade that doubles as brand marketing.",
    "year": "2022",
    "client": "Great Lands Auto Plc",
    "type": "mixed-use",
    "cost": "68Million",
    "location": "Bishoftu, Ethiopia",
    "challenges": "Designing a structure that balances aesthetic appeal with practical considerations for large vehicle movement and display.",
    "tags": ["Buildings", "Mixed Use"]
  },
  {
    "id": "31",
    "title": "Restaurant Mixed Use Building",
    "coverImage": "images/projects/mixed use bldg/6.png",
    "images": ["images/projects/mixed use bldg/6.png"],
    "hero": "icons/Buildings/building-line.svg",
    "description": "This two-story mixed-use property in Addis Ababa houses a vibrant ground-floor restaurant with expansive outdoor terraces and upper-level rental units. The architecture encourages cross-ventilation and blends warm interior finishes with a minimal urban façade.",
    "year": "2022",
    "client": "Private Client",
    "type": "mixed-use",
    "cost": "10Million",
    "location": "Addis Ababa, Ethiopia",
    "challenges": "Ensuring proper sound and odor insulation between the restaurant and upper-level residences.",
    "tags": ["Buildings", "Mixed Use"]
  },
  {
    "id": "32",
    "title": "Mixed Use Building",
    "coverImage": "images/projects/mixed use bldg/7.jpg",
    "images": ["images/projects/mixed use bldg/7.jpg"],
    "hero": "icons/Buildings/building-line.svg",
    "description": "A compact urban development in Mertu Le Mariyam combining office spaces on lower levels with residential apartments above. The façade uses local stone cladding to reflect regional heritage while incorporating modern balcony designs for improved living comfort.",
    "year": "2022",
    "client": "Mamaru and Friends",
    "type": "mixed-use",
    "cost": "47Million",
    "location": "Mertu Le Mariyam, Gojam, Ethiopia",
    "challenges": "Maximizing usable space on a narrow plot while maintaining distinct entry points for commercial and residential users.",
    "tags": ["Buildings", "Mixed Use"]
  },
  {
    "id": "33",
    "title": "Irrecha Tower, Cultural Center Building",
    "coverImage": "images/projects/mixed use bldg/8.jpg",
    "images": ["images/projects/mixed use bldg/8.jpg"],
    "hero": "icons/Buildings/building-line.svg",
    "description": "A landmark cultural hub in Bishoftu, Irrecha Tower incorporates performance halls, event spaces, and cultural exhibition areas in a vertical arrangement. The design integrates symbolic patterns inspired by Oromo heritage while prioritizing flexible interior layouts for diverse events.",
    "year": "2012",
    "client": "Private Client",
    "type": "mixed-use",
    "cost": "786.3Million",
    "location": "Bishoftu, Ethiopia",
    "challenges": "Translating cultural symbolism into functional architectural elements without losing modern functionality.",
    "tags": ["Buildings", "Cultural Center"]
  },
  {
    "id": "34",
    "title": "Mixed Hotel Building",
    "coverImage": "images/projects/mixed use bldg/11.jpg",
    "images": ["images/projects/mixed use bldg/11.jpg"],
    "hero": "icons/Buildings/building-line.svg",
    "description": "This hotel in Holeta Town integrates conference facilities, a rooftop lounge, and street-facing retail spaces. The design incorporates panoramic glazing to capture mountain views and warm interiors influenced by Ethiopian hospitality traditions.",
    "year": "2012",
    "client": "Engineer Dirba Defersha",
    "type": "mixed-use",
    "cost": "503Million",
    "location": "Holeta Town, Ethiopia",
    "challenges": "Creating a harmonious experience for hotel guests while maintaining accessibility and vibrancy for public commercial zones.",
    "tags": ["Buildings", "Mixed Use"]
  },
  {
    "id": "35",
    "title": "Guest House Building",
    "coverImage": "images/projects/mixed use bldg/12.png",
    "images": ["images/projects/mixed use bldg/12.png"],
    "hero": "icons/Buildings/building-line.svg",
    "description": "A welcoming guest house in Bishoftu designed for both short and long-term stays. The structure combines homely interiors with landscaped courtyards, blending traditional Ethiopian motifs with modern spatial efficiency.",
    "year": "2012",
    "client": "Tsehay Shume",
    "type": "mixed-use",
    "cost": "59Million",
    "location": "Bishoftu, Ethiopia",
    "challenges": "Ensuring guest privacy while preserving open communal areas for interaction.",
    "tags": ["Buildings", "Mixed Use"]
  },
  {
    "id": "36",
    "title": "Restaurant Mixed Use Building",
    "coverImage": "images/projects/mixed use bldg/13.jpg",
    "images": ["images/projects/mixed use bldg/13.jpg"],
    "hero": "icons/Buildings/building-line.svg",
    "description": "Located in Nazreth, this property integrates a bustling street-level restaurant with office spaces above. The hospitality area features open-air dining and street outreach, while the upper floors focus on functional workspaces with natural lighting.",
    "year": "2012",
    "client": "Mama Ethiopia",
    "type": "mixed-use",
    "cost": "1.8Million",
    "location": "Nazreth, Ethiopia",
    "challenges": "Managing daily restaurant operations without disturbing the productivity of upstairs businesses.",
    "tags": ["Buildings", "Restaurant"]
  },
  {
    "id": "37",
    "title": "Mixed Commercial Building",
    "coverImage": "images/projects/mixed use bldg/14.png",
    "images": ["images/projects/mixed use bldg/14.png"],
    "hero": "icons/Buildings/building-line.svg",
    "description": "This multi-purpose complex in Nazreth includes retail units, professional offices, and an events hall. A modern façade and large atrium enhance the shopping and work environment while providing an adaptable infrastructure for tenant needs.",
    "year": "2017",
    "client": "Kayo Loni Plc",
    "type": "mixed-use",
    "cost": "503Million",
    "location": "Nazreth, Ethiopia",
    "challenges": "Designing HVAC and circulation systems to suit a variety of tenant functions within a single building envelope.",
    "tags": ["Buildings", "Mixed Use"]
  },
  {
    "id": "38",
    "title": "Museums Building",
    "coverImage": "images/projects/museums/1.jpg",
    "images": ["images/projects/museums/1.jpg"],
    "hero": "icons/Buildings/apartment-line.svg",
    "description": "Situated in Mertu Le Mariyam, this museum blends modern architecture with exhibits highlighting local history and faith. The building features climate-controlled galleries, skylit atriums, and strategic circulation paths that guide visitors through curated narratives while maintaining visual connections to the surrounding townscape.",
    "year": "2015",
    "client": "Mertu Le Mariyam Church Committee",
    "type": "Museum",
    "cost": "35Million",
    "location": "Mertu Le Mariyam, Gojam, Ethiopia",
    "challenges": "Designing gallery spaces that preserve delicate artifacts while accommodating fluctuating visitor numbers.",
    "tags": ["Buildings", "Museums"]
  },
  {
    "id": "39",
    "title": "Office Building",
    "coverImage": "images/projects/office/1.jpg",
    "images": ["images/projects/office/1.jpg"],
    "hero": "icons/Buildings/apartment-line.svg",
    "description": "In Addis Ababa’s central business district, this office building offers open-plan workstations, breakout zones, and client reception lounges. Floor-to-ceiling glazing maximizes daylight, while custom shading systems reduce glare and improve thermal comfort for employees.",
    "year": "2015",
    "client": "Private Client",
    "type": "Office",
    "cost": "~",
    "location": "Addis Ababa, Ethiopia",
    "challenges": "Balancing a high-density workspace with ergonomic and acoustic comfort for long-term productivity.",
    "tags": ["Buildings", "Office"]
  },
  {
    "id": "40",
    "title": "Administration Building",
    "coverImage": "images/projects/office/2.jpg",
    "images": ["images/projects/office/2.jpg"],
    "hero": "icons/Buildings/apartment-line.svg",
    "description": "Serving as the administrative headquarters for a local institution in Nazreth, this building emphasizes clear functional zoning — public service halls on lower floors and secure staff areas above. The design incorporates natural ventilation, durable finishes, and an accessible layout.",
    "year": "2016",
    "client": "Mama Ethiopia",
    "type": "Office",
    "cost": "85Million",
    "location": "Nazreth, Ethiopia",
    "challenges": "Ensuring a welcoming public interface while maintaining secure, private areas for sensitive operations.",
    "tags": ["Buildings", "Administration"]
  },
  {
    "id": "41",
    "title": "Residencial Building",
    "coverImage": "images/projects/residence/3.jpg",
    "images": ["images/projects/residence/3.jpg"],
    "hero": "icons/Buildings/apartment-line.svg",
    "description": "A multi-family residence in Addis Ababa designed with family-focused layouts, private balconies, and landscaped communal courtyards. The structure makes use of natural stone cladding paired with modern detailing to provide warmth and durability.",
    "year": "2016",
    "client": "Ato Samson Taddesse",
    "type": "Residential",
    "cost": "2.5Million",
    "location": "Addis Ababa, Ethiopia",
    "challenges": "Incorporating shared spaces that foster community while preserving individual family privacy.",
    "tags": ["Buildings", "Residential"]
  },
  {
    "id": "42",
    "title": "Residencial Building",
    "coverImage": "images/projects/residence/4.jpg",
    "images": ["images/projects/residence/4.jpg"],
    "hero": "icons/Buildings/apartment-line.svg",
    "description": "This Addis Ababa home combines modern design principles with Ethiopian decorative elements. Large windows capture city views, while a careful floor plan optimizes natural light and ventilation across all rooms.",
    "year": "2016",
    "client": "W/o Yewbdar Meles",
    "type": "Residential",
    "cost": "2.2Million",
    "location": "Addis Ababa, Ethiopia",
    "challenges": "Creating a comfortable, naturally lit interior within the constraints of a compact urban plot.",
    "tags": ["Buildings", "Residential"]
  },
  {
    "id": "43",
    "title": "Residencial Building",
    "coverImage": "images/projects/residence/5.jpg",
    "images": ["images/projects/residence/5.jpg"],
    "hero": "icons/Buildings/apartment-line.svg",
    "description": "A private residence in Addis Ababa featuring expansive living spaces, a rooftop terrace, and a blend of modern and classic finishes. The house is tailored for both formal entertaining and everyday family life.",
    "year": "2016",
    "client": "Kolonel Asrat Tessema",
    "type": "Residential",
    "cost": "4.3Million",
    "location": "Addis Ababa, Ethiopia",
    "challenges": "Integrating luxury features without compromising functional daily living areas.",
    "tags": ["Buildings", "Residential"]
  },
  {
    "id": "44",
    "title": "Elementary School",
    "coverImage": "images/projects/school/1.jpg",
    "images": ["images/projects/school/1.jpg"],
    "hero": "icons/Document/book-open-line.svg",
    "description": "A modern primary school in Addis Ababa with adaptable classrooms, shaded outdoor play areas, and student-centered learning zones. Bright colors and natural daylight enhance the learning atmosphere, while the design prioritizes safety and accessibility.",
    "year": "2013",
    "client": "Bole Medhanealem Church Committee",
    "type": "School",
    "cost": "62Million",
    "location": "Addis Ababa, Ethiopia",
    "challenges": "Creating a stimulating learning environment that supports varied teaching styles and age groups.",
    "tags": ["Buildings", "Document", "Design"]
  },
  {
    "id": "45",
    "title": "High School Building",
    "coverImage": "images/projects/school/2.jpg",
    "images": ["images/projects/school/2.jpg", "images/projects/school/2.1.jpg"],
    "hero": "icons/Document/book-read-line.svg",
    "description": "A full-scale renovation of a high school in Addis Ababa that modernized classrooms, science labs, and sports facilities. The upgrade included new energy-efficient mechanical systems, improved accessibility, and updated technology integration for digital learning.",
    "year": "2024",
    "client": "Addis Ababa Education Bureau",
    "type": "School",
    "cost": "82Million",
    "location": "Addis Ababa, Ethiopia",
    "challenges": "Coordinating construction schedules around ongoing classes to minimize disruption for students and faculty.",
    "tags": ["Buildings", "Renovation"]
  },
  {
    "id": "46",
    "title": "Bole Medhanealem Church",
    "coverImage": "images/church.jpg",
    "images": ["images/bole-med.png", "images/church.jpg"],
    "hero": "icons/Buildings/building-line.svg",
    "description": "Completed in 2005, this expansion project for Bole Medhanealem Church in Addis Ababa carefully blended traditional Ethiopian Orthodox architectural elements with discreet modern upgrades. The work included extending the main prayer hall, adding auxiliary facilities for community gatherings, and enhancing structural durability. Natural stone masonry and detailed iconography preserve the church’s spiritual identity, while improved lighting and ventilation elevate the worship experience.",
    "year": "2005",
    "client": "Bole Medhanealem Church",
    "type": "Church",
    "cost": "~",
    "location": "Addis Ababa, Ethiopia",
    "challenges": "Maintaining uninterrupted religious services during construction while safeguarding historic features and sacred artworks.",
    "tags": ["Buildings", "Religious", "Design"]
  },

]
